# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_hobbies_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=32)),
                ('area', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='url',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
