# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbies',
            name='year',
            field=models.CharField(default=django.utils.timezone.now, max_length=16),
            preserve_default=False,
        ),
    ]
