# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20170127_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='organization',
            field=models.CharField(default='default', max_length=32),
            preserve_default=False,
        ),
    ]
