# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20170127_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='education',
            name='specialization',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='organization',
            name='adress',
            field=models.CharField(blank=True, max_length=32, verbose_name='adress'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='area',
            field=models.CharField(max_length=32, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=32, verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='region',
            field=models.CharField(max_length=32, verbose_name='region'),
        ),
    ]
