# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20170127_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='period',
        ),
        migrations.RemoveField(
            model_name='work',
            name='period',
        ),
        migrations.AlterField(
            model_name='organization',
            name='adress',
            field=models.CharField(blank=True, max_length=32, verbose_name='Adress'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='area',
            field=models.CharField(max_length=32, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Organization name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='region',
            field=models.CharField(max_length=32, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='work',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Organization', verbose_name='Organization name'),
        ),
    ]
