# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20170127_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbies',
            name='year',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Organization name'),
        ),
    ]
