# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20170221_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='project',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='work',
            name='url_project',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
