# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_work_short_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='adress',
            new_name='address',
        ),
        migrations.AddField(
            model_name='work',
            name='respons',
            field=models.ForeignKey(blank=True, default='n\x07', on_delete=django.db.models.deletion.CASCADE, to='mainapp.Respons', verbose_name='Responsibilities'),
            preserve_default=False,
        ),
    ]
